version: 0.0
os: linux 
files:
  - source: /index.js
    destination: /home/ubuntu/nodejs_ec2_pipeline/
permission:
  - object: script/
    pattern: "*.sh"
    owner: root
    mode: 755
hooks:
  ApplicationStop:
    - location: script/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 300
      runas: root