version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/nodejs-pipeline-demo
hooks:
  ApplicationStop:
    - location: script/application_stop.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: script/before_container_start.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: script/application_container_start.sh
      timeout: 60
      runas: ubuntu