version: 0.0
os: linux 
files:
  - source: index.js
    destination: /home/ubuntu/nodejs_ec2_pipeline/

hooks:
  ApplicationStop:
    - location: script/application_stop.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 60
      runas: ubuntu